### PR TITLE
Sp 57 bottom drawer fix

### LINKED ISSUE #57: sp-47 bottomDrawer implementation interferes with navDrawer
- Description: bottomDrawer implementation interferes with navDrawer and causes visual bugs as shown below:
image

The issue does not seem to affect functionality or any other pages where bottomDrawer is not in use.

- Cause: unknown
- Resolution: unknown

### PR DESCRIPTION
**Pull request by mnashat**
merging bottom drawer fix into virtual study room branch (original branch in which bottom drawer was implemented)

Closes #57

### CODE REVIEW

**Review by kikkiii21 — APPROVED** [review]
Good job on the bug. The nav menu has the full length now

File: src/components/StudyRoom/BottomDrawer.js [hunk 1]
```diff
@@ -27,27 +27,44 @@ const Puller = styled(Box)(({theme}) => ({
...
+                            borderTopRightRadius: '20px'
+                        },
+                    }}
+                />
+                :
+                <></>
+            }
             {/*<Box sx={{ textAlign: 'center', pt: 1 }}>*/}
             <Button style={{width: '100%', height: '100%', background: 'none', border: 'none'}}
                     onClick={toggleDrawer(true)}>{props.icon}</Button>
```
Comment (guaj) [inline src/components/StudyRoom/BottomDrawer.js:70]: why call this function async if you neither await nor use the promise ?

**Review by guaj — APPROVED** [review]

File: src/components/StudyRoom/BottomDrawer.js (hunk 1 above)
Comment (mnashat) [reply src/components/StudyRoom/BottomDrawer.js:70]: Because the delay method is async and I cannot call an asynchronous function inside a synchronous one.
